twitter: "https://twitter.com/"
github: "https://github.com/"
instagram: "https://www.instagram.com/hwtechclub/?hl=en"
linkedin: "https://www.linkedin.com/"
dribbble: "https://dribbble.com/"
youtube: "https://youtube.com"
facebook: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
